server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      embedding:
        enabled: false
      chat:
        options:
          model: qwen-max
    openai:
      base-url: https://maas-api.ai-yuanjing.com/openapi/compatible-mode
      api-key: ${AI_MAAS_API_KEY}
      embeddings-path: /embeddings
      chat:
        options:
          model: gpt-oss-120b
          stream: false
      embedding:
        enabled: true
        options:
          model: qwen3-embed-0.6b
#    mcp:
#      client:
#        enabled: false
#        request-timeout: 50000
#        name: clft-agent-client
#        toolcallback:
#          enabled: true
#        sse:
#          connections:
#            clft-agent-client:
#              url: http://172.16.22.18:8081/mcp/sec-classify-level/
#            colt-agent-client:
#              url: http://172.16.22.18:8081/mcp/sec-collector-management/
#        version: 1.0.0
  mandatory-file-encoding: UTF-8

logging:
  level:
    io:
      modelcontextprotocol:
        client: INFO
        spec: INFO


similarity:
  match:
    url: https://172.16.22.18:8901/py/match
    timeout: 30000
