server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        request-timeout: 50000
        name: clft-agent-client
        toolcallback:
          enabled: true
        sse:
          connections:
            clft-agent-client:
              url: http://192.168.33.115:8081/mcp/sec-classify-level/
        version: 1.0.0
  mandatory-file-encoding: UTF-8

logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
