server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: clft-agent
  ai:
    openai:
      base-url: http://134.0.111.209:10025/v1/chat/completions
      api-key: ${AI_MAAS_API_KEY}
      chat:
        options:
          model: deepseek_70b
          stream: false
    ollama:
      base-url: http://134.0.111.206:11434
      embedding:
        model: bge-m3:567m

  mandatory-file-encoding: UTF-8

logging:
  level:
    io:
      modelcontextprotocol:
        client: INFO
        spec: INFO


similarity:
  match:
    url: http://134.0.111.206:8899/match
    timeout: 30000

rag:
  source: classpath:rag/rag_friendly_classification.txt
  vector-file-path: file:/app/resources/vectors/classification_vectors.json
