server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp
  ai:
    openai:
      base-url: http://134.0.111.209:10025/v1
      api-key: ${AI_MAAS_API_KEY}
      chat:
        options:
          model: deepseek_70b
          stream: false
      embedding:
        base-url:  http://134.0.111.206:11434/api/embeddings
        enabled: true
        api-key: ${AI_EMBEDDING_API_KEY}
        options:
          model: bge-m3:567m

  mandatory-file-encoding: UTF-8

logging:
  level:
    io:
      modelcontextprotocol:
        client: INFO
        spec: INFO


similarity:
  match:
    url: http://134.0.111.206:8899/match
    timeout: 30000

rag:
  source: classpath:rag/rag_friendly_classification.txt
  vector-file-path: file:/app/resources/vectors/classification_vectors.json
